name: CI/CD with Cloud Build and Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.GCLOUD_SA_KEY}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd:${{ github.sha }}
          registry: gcr.io
          additional_tags: |
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy pogs-cicd \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd:${{ github.sha }} \
            --platform=managed \
            --region=your-preferred-region \
            --allow-unauthenticated

# Add additional steps here if required, like running tests or other checks before deployment.
