name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd:${{ github.sha }}
          registry: gcr.io
          additional_tags: |
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd:latest

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy test-cicd \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd:${{ github.sha }} \
            --platform=managed \
            --region=northamerica-northeast1 \
            --allow-unauthenticated
