name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{secrets.GCLOUD_SA_KEY}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-cicd .
        working-directory: PATH_TO_DOCKERFILE_DIRECTORY

      - name: Push Docker image to Google Cloud Artifact Registry
        run: |
          docker tag my-cicd gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd
        working-directory: PATH_TO_DOCKERFILE_DIRECTORY

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy test-cicd \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-cicd \
            --platform=managed \
            --region=northamerica-northeast1 \
            --allow-unauthenticated
